### ISSUE TITLE
Отсутствует атрибут alt в изображениях 

### ISSUE THREAD

**Issue by ikrieg** [netology-code/git-homeworks-neuro-pr#1]
В файле index.html у изображений отсутствует значение атрибута `alt`, в связи с этим скрин-ридеры не могут корректно "прочитать" изображения.

**Comment by DenisBolbeko** [comment]
В файле index.html у изображений добавлено значение атрибута `alt`.
Ссылка на  Pull requests [https://github.com/netology-code/git-homeworks-neuro-pr/pulls]

**Comment by Pager-290583** [comment]
Добавил alt к изображениям на странице index.html

**Comment by ekaterinabauer** [comment]
# Добавлены атрибуты alt к изображениям #59

**Comment by denis-luttcev** [comment]
Solution proposed: denis-luttcev:accessibility/image-alt-attributes
Pull Request: https://github.com/netology-code/git-homeworks-neuro-pr/pull/71
