### ISSUE TITLE
Главная страница. Текстовый блок "Оставайтесь на связи" не правильно переносится

### ISSUE THREAD

**Issue by NikiHollywood** [netology-code/git-homeworks-neuro-pr#1138]
@solarrust

# Описание проблемы
#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."
3. Перейти в режим мобильная версия 400px и ниже до 320px

#### Ожидаемый результат:

Текст слово "Оставайтесь" не переносится на следующую строку

#### Фактический результат:

Текст переносится на следующую строку (см. скриншот)

#### Программное окружение:
* Устройство: iPhone 11 (iOS 13.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншот
<img src="https://camo.githubusercontent.com/8b6aa0acc22de5c12c5a449f639cc7e430299d13757d046bf63f9f010175d210/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67" alt="" data-canonical-src="https://i.imgur.com/HcSpYkT.png" style="max-width:100%;">

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
