### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by ki1n** [netology-code/git-homeworks-neuro-pr#475]
@solarrust
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

#### Ожидаемый результат

Текст занимает не больше двух строк.

#### Фактический результат

Текст занимает 3-4 строчки.

#### Программное окружение

* Устройство: iPhone 8+ (iOS 12.1)
* Браузер: Chrome (70.0.3538.75)

#### Скриншоты

![](https://camo.githubusercontent.com/0d8b55198e03e6e941c820b3ac1c974ef3fe3c89/68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67)

**Comment by ki1n** [comment]
Add Forms

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
